// Pre-training data for the voice AI learning store.
// Maps common spoken phrases (Hindi, Telugu, Tamil, Kannada, English) to
// catalog product names.
//
// count = 3 → auto-confirm (unambiguous, only one reasonable product)
// count = 2 → boost ranking (confirm once more to lock in)

export const SEED_TRAINING = [

  // ── Sugar & Salt ────────────────────────────────────────
  { spoken: "cheeni",          product: "Sugar 1kg",                       count: 3 },
  { spoken: "shakkar",         product: "Sugar 1kg",                       count: 3 },
  { spoken: "chini",           product: "Sugar 1kg",                       count: 3 },
  { spoken: "namak",           product: "Tata Salt 1kg",                   count: 3 },
  { spoken: "uppu",            product: "Tata Salt 1kg",                   count: 2 },
  { spoken: "gud",             product: "Jaggery 1kg",                     count: 3 },
  { spoken: "gur",             product: "Jaggery 1kg",                     count: 3 },
  { spoken: "bellam",          product: "Jaggery 1kg",                     count: 3 },
  { spoken: "vellam",          product: "Jaggery 1kg",                     count: 2 },

  // ── Flour & Grains ──────────────────────────────────────
  { spoken: "atta",            product: "Aashirvaad Atta 5kg",             count: 3 },
  { spoken: "aata",            product: "Aashirvaad Atta 5kg",             count: 3 },
  { spoken: "gehun atta",      product: "Aashirvaad Atta 5kg",             count: 3 },
  { spoken: "godhuma pindi",   product: "Aashirvaad Atta 5kg",             count: 2 },
  { spoken: "godhi hittu",     product: "Aashirvaad Atta 5kg",             count: 2 },
  { spoken: "maida",           product: "Maida 1kg",                       count: 3 },
  { spoken: "refined flour",   product: "Maida 1kg",                       count: 3 },
  { spoken: "besan",           product: "Besan 1kg",                       count: 3 },
  { spoken: "gram flour",      product: "Besan 1kg",                       count: 3 },
  { spoken: "chana flour",     product: "Besan 1kg",                       count: 3 },
  { spoken: "suji",            product: "Suji 500g",                       count: 3 },
  { spoken: "rava",            product: "Suji 500g",                       count: 3 },
  { spoken: "semolina",        product: "Suji 500g",                       count: 3 },
  { spoken: "poha",            product: "Poha 500g",                       count: 3 },
  { spoken: "beaten rice",     product: "Poha 500g",                       count: 3 },
  { spoken: "flattened rice",  product: "Poha 500g",                       count: 3 },

  // ── Rice ────────────────────────────────────────────────
  { spoken: "chawal",          product: "Sona Masoori Rice 5kg",           count: 2 },
  { spoken: "biyyam",          product: "Sona Masoori Rice 5kg",           count: 2 },
  { spoken: "akki",            product: "Sona Masoori Rice 5kg",           count: 2 },
  { spoken: "arisi",           product: "Sona Masoori Rice 5kg",           count: 2 },
  { spoken: "sona masoori",    product: "Sona Masoori Rice 5kg",           count: 3 },
  { spoken: "sona masuri",     product: "Sona Masoori Rice 5kg",           count: 3 },
  { spoken: "basmati",         product: "India Gate Basmati 1kg",          count: 3 },
  { spoken: "basmati chawal",  product: "India Gate Basmati 1kg",          count: 3 },
  { spoken: "ponni",           product: "Ponni Rice 5kg",                  count: 3 },
  { spoken: "idli rice",       product: "Idli Rice 1kg",                   count: 3 },

  // ── Dals & Pulses ───────────────────────────────────────
  { spoken: "toor dal",        product: "Toor Dal 1kg",                    count: 3 },
  { spoken: "arhar dal",       product: "Toor Dal 1kg",                    count: 3 },
  { spoken: "tur dal",         product: "Toor Dal 1kg",                    count: 3 },
  { spoken: "kandi pappu",     product: "Toor Dal 1kg",                    count: 3 },
  { spoken: "togari bele",     product: "Toor Dal 1kg",                    count: 2 },
  { spoken: "moong dal",       product: "Moong Dal 1kg",                   count: 3 },
  { spoken: "mung dal",        product: "Moong Dal 1kg",                   count: 3 },
  { spoken: "pesara pappu",    product: "Moong Dal 1kg",                   count: 2 },
  { spoken: "chana dal",       product: "Chana Dal 1kg",                   count: 3 },
  { spoken: "senaga pappu",    product: "Chana Dal 1kg",                   count: 2 },
  { spoken: "urad dal",        product: "Urad Dal 1kg",                    count: 3 },
  { spoken: "urid dal",        product: "Urad Dal 1kg",                    count: 3 },
  { spoken: "minapa pappu",    product: "Urad Dal 1kg",                    count: 2 },
  { spoken: "masoor dal",      product: "Masoor Dal 1kg",                  count: 3 },
  { spoken: "masoor",          product: "Masoor Dal 1kg",                  count: 3 },
  { spoken: "red lentil",      product: "Masoor Dal 1kg",                  count: 3 },
  { spoken: "rajma",           product: "Rajma 1kg",                       count: 3 },
  { spoken: "kidney beans",    product: "Rajma 1kg",                       count: 3 },
  { spoken: "chole",           product: "Kabuli Chana 1kg",                count: 3 },
  { spoken: "kabuli chana",    product: "Kabuli Chana 1kg",                count: 3 },
  { spoken: "chickpeas",       product: "Kabuli Chana 1kg",                count: 3 },
  { spoken: "moth dal",        product: "Moth Dal 500g",                   count: 3 },
  { spoken: "matki",           product: "Moth Dal 500g",                   count: 3 },

  // ── Dairy ───────────────────────────────────────────────
  { spoken: "doodh",           product: "Amul Milk 1L",                    count: 2 },
  { spoken: "dudh",            product: "Amul Milk 1L",                    count: 2 },
  { spoken: "palu",            product: "Amul Milk 1L",                    count: 2 },
  { spoken: "paal",            product: "Amul Milk 1L",                    count: 2 },
  { spoken: "amul milk",       product: "Amul Milk 1L",                    count: 3 },
  { spoken: "dahi",            product: "Amul Curd 400g",                  count: 2 },
  { spoken: "perugu",          product: "Amul Curd 400g",                  count: 2 },
  { spoken: "thayir",          product: "Amul Curd 400g",                  count: 2 },
  { spoken: "ghee",            product: "Amul Ghee 1L",                    count: 2 },
  { spoken: "desi ghee",       product: "Amul Ghee 1L",                    count: 3 },
  { spoken: "neyyi",           product: "Amul Ghee 1L",                    count: 2 },
  { spoken: "nei",             product: "Amul Ghee 1L",                    count: 2 },
  { spoken: "butter",          product: "Amul Butter 100g",                count: 2 },
  { spoken: "makhan",          product: "Amul Butter 100g",                count: 2 },
  { spoken: "makkhan",         product: "Amul Butter 100g",                count: 2 },
  { spoken: "paneer",          product: "Amul Paneer 200g",                count: 3 },
  { spoken: "cottage cheese",  product: "Amul Paneer 200g",                count: 3 },
  { spoken: "anda",            product: "Eggs (6pc)",                      count: 3 },
  { spoken: "egg",             product: "Eggs (6pc)",                      count: 2 },

  // ── Oils ────────────────────────────────────────────────
  { spoken: "sunflower oil",   product: "Fortune Sunflower Oil 1L",        count: 3 },
  { spoken: "suraj mukhi tel", product: "Fortune Sunflower Oil 1L",        count: 3 },
  { spoken: "coconut oil",     product: "Parachute Coconut Oil 500ml",     count: 3 },
  { spoken: "nariyal tel",     product: "Parachute Coconut Oil 500ml",     count: 3 },
  { spoken: "palakaya nune",   product: "Parachute Coconut Oil 500ml",     count: 2 },
  { spoken: "mustard oil",     product: "Mustard Oil 1L",                  count: 3 },
  { spoken: "sarson ka tel",   product: "Mustard Oil 1L",                  count: 3 },
  { spoken: "sarson tel",      product: "Mustard Oil 1L",                  count: 3 },
  { spoken: "groundnut oil",   product: "Groundnut Oil 1L",                count: 3 },
  { spoken: "mungfali tel",    product: "Groundnut Oil 1L",                count: 3 },
  { spoken: "peanut oil",      product: "Groundnut Oil 1L",                count: 3 },
  { spoken: "sesame oil",      product: "Sesame Oil 200ml",                count: 3 },
  { spoken: "til ka tel",      product: "Sesame Oil 200ml",                count: 3 },
  { spoken: "gingelly oil",    product: "Sesame Oil 200ml",                count: 3 },
  { spoken: "nalla ennai",     product: "Sesame Oil 200ml",                count: 2 },

  // ── Spices ──────────────────────────────────────────────
  { spoken: "haldi",           product: "Tata Sampann Turmeric 200g",      count: 3 },
  { spoken: "turmeric",        product: "Tata Sampann Turmeric 200g",      count: 3 },
  { spoken: "pasupu",          product: "Tata Sampann Turmeric 200g",      count: 2 },
  { spoken: "manjal",          product: "Tata Sampann Turmeric 200g",      count: 2 },
  { spoken: "mirchi podi",     product: "Tata Sampann Chilli 200g",        count: 3 },
  { spoken: "lal mirch",       product: "Tata Sampann Chilli 200g",        count: 3 },
  { spoken: "red chilli",      product: "Tata Sampann Chilli 200g",        count: 3 },
  { spoken: "dhania",          product: "Tata Sampann Coriander",          count: 3 },
  { spoken: "kothimera",       product: "Tata Sampann Coriander",          count: 2 },
  { spoken: "kothamalli",      product: "Tata Sampann Coriander",          count: 2 },
  { spoken: "jeera",           product: "Cumin Seeds 100g",                count: 3 },
  { spoken: "jilakarra",       product: "Cumin Seeds 100g",                count: 2 },
  { spoken: "seeragam",        product: "Cumin Seeds 100g",                count: 2 },
  { spoken: "rai",             product: "Mustard Seeds 100g",              count: 3 },
  { spoken: "avalu",           product: "Mustard Seeds 100g",              count: 2 },
  { spoken: "kadugu",          product: "Mustard Seeds 100g",              count: 2 },
  { spoken: "hing",            product: "Hing 25g",                        count: 3 },
  { spoken: "asafoetida",      product: "Hing 25g",                        count: 3 },
  { spoken: "perungayam",      product: "Hing 25g",                        count: 2 },
  { spoken: "ajwain",          product: "Ajwain 100g",                     count: 3 },
  { spoken: "carom seeds",     product: "Ajwain 100g",                     count: 3 },
  { spoken: "garam masala",    product: "MDH Garam Masala 100g",           count: 3 },
  { spoken: "chaat masala",    product: "MDH Chaat Masala 100g",           count: 3 },
  { spoken: "kali mirch",      product: "Black Pepper Powder 50g",         count: 3 },
  { spoken: "black pepper",    product: "Black Pepper Powder 50g",         count: 3 },

  // ── Beverages ───────────────────────────────────────────
  { spoken: "chai",            product: "Tata Tea Gold 250g",              count: 2 },
  { spoken: "tata tea",        product: "Tata Tea Gold 250g",              count: 3 },
  { spoken: "red label",       product: "Red Label Tea 250g",              count: 3 },
  { spoken: "three roses",     product: "Three Roses Tea 250g",            count: 3 },
  { spoken: "bru",             product: "Bru Coffee 50g",                  count: 3 },
  { spoken: "nescafe",         product: "Nescafe Classic 50g",             count: 3 },

  // ── Packaged / FMCG ─────────────────────────────────────
  { spoken: "maggi",           product: "Maggi Noodles 70g",               count: 3 },
  { spoken: "noodles",         product: "Maggi Noodles 70g",               count: 2 },
  { spoken: "parle g",         product: "Parle-G Biscuits 500g",           count: 3 },
  { spoken: "parleg",          product: "Parle-G Biscuits 500g",           count: 3 },
  { spoken: "glucose biscuit", product: "Parle-G Biscuits 500g",           count: 3 },
  { spoken: "good day",        product: "Britannia Good Day 200g",         count: 3 },
  { spoken: "marie gold",      product: "Britannia Marie Gold 250g",       count: 3 },
  { spoken: "hide and seek",   product: "Parle Hide & Seek 100g",          count: 3 },
  { spoken: "bourbon",         product: "Britannia Bourbon 100g",          count: 3 },
  { spoken: "oreo",            product: "Oreo 120g",                       count: 3 },
  { spoken: "lays",            product: "Lays Chips 26g",                  count: 3 },
  { spoken: "chips",           product: "Lays Chips 26g",                  count: 2 },
  { spoken: "kurkure",         product: "Kurkure 90g",                     count: 3 },
  { spoken: "kurkuri",         product: "Kurkure 90g",                     count: 3 },
  { spoken: "bingo",           product: "Bingo 90g",                       count: 3 },
  { spoken: "namkeen",         product: "Haldiram Namkeen 200g",           count: 2 },
  { spoken: "bhujia",          product: "Haldiram Bhujia 200g",            count: 3 },
  { spoken: "sev",             product: "Haldiram Sev 200g",               count: 3 },
  { spoken: "murmura",         product: "Puffed Rice 200g",                count: 3 },
  { spoken: "mamra",           product: "Puffed Rice 200g",                count: 3 },
  { spoken: "popcorn",         product: "Popcorn 100g",                    count: 2 },

  // ── Health & Nutrition ───────────────────────────────
  { spoken: "horlicks",        product: "Horlicks 500g",                   count: 3 },
  { spoken: "boost",           product: "Boost 500g",                      count: 3 },
  { spoken: "bournvita",       product: "Bournvita 500g",                  count: 3 },
  { spoken: "complan",         product: "Complan 500g",                    count: 3 },
  { spoken: "glucon d",        product: "Glucon D 200g",                   count: 3 },
  { spoken: "glucond",         product: "Glucon D 200g",                   count: 3 },
  { spoken: "ensure",          product: "Ensure 400g",                     count: 3 },
  { spoken: "protinex",        product: "Protinex 250g",                   count: 3 },
  { spoken: "ors",             product: "ORS Sachet",                      count: 3 },
  { spoken: "electral",        product: "Electral Powder",                 count: 3 },

  // ── Personal Care (Toothpaste / Brush) ───────────────
  { spoken: "colgate",         product: "Colgate Strong Teeth 200g",       count: 3 },
  { spoken: "pepsodent",       product: "Pepsodent 200g",                  count: 3 },
  { spoken: "sensodyne",       product: "Sensodyne 70g",                   count: 3 },
  { spoken: "closeup",         product: "Close Up 200g",                   count: 3 },
  { spoken: "dabur red",       product: "Dabur Red Toothpaste 200g",       count: 3 },
  { spoken: "toothbrush",      product: "Toothbrush",                      count: 2 },
  { spoken: "brush",           product: "Toothbrush",                      count: 2 },

  // ── Soaps ────────────────────────────────────────────
  { spoken: "sabun",           product: "Lifebuoy Soap 100g",              count: 2 },
  { spoken: "lifebuoy",        product: "Lifebuoy Soap 100g",              count: 3 },
  { spoken: "lux",             product: "Lux Soap 100g",                   count: 3 },
  { spoken: "dove soap",       product: "Dove Soap 100g",                  count: 3 },
  { spoken: "pears",           product: "Pears Soap 75g",                  count: 3 },
  { spoken: "dettol soap",     product: "Dettol Soap 100g",                count: 3 },
  { spoken: "santoor",         product: "Santoor Soap 100g",               count: 3 },
  { spoken: "mysore sandal",   product: "Mysore Sandal Soap 150g",         count: 3 },
  { spoken: "cinthol",         product: "Cinthol Soap 100g",               count: 3 },

  // ── Shampoo & Hair Care ──────────────────────────────
  { spoken: "shampoo",         product: "Shampoo",                         count: 2 },
  { spoken: "head and shoulders", product: "Head & Shoulders 180ml",       count: 3 },
  { spoken: "clinic plus",     product: "Clinic Plus 180ml",               count: 3 },
  { spoken: "pantene",         product: "Pantene 180ml",                   count: 3 },
  { spoken: "dove shampoo",    product: "Dove Shampoo 180ml",              count: 3 },
  { spoken: "sunsilk",         product: "Sunsilk 180ml",                   count: 3 },
  { spoken: "parachute hair oil", product: "Parachute Hair Oil 200ml",     count: 3 },
  { spoken: "nihar",           product: "Nihar Hair Oil 200ml",            count: 3 },

  // ── Skin Care ────────────────────────────────────────
  { spoken: "nivea cream",     product: "Nivea Cream 100ml",               count: 3 },
  { spoken: "vaseline",        product: "Vaseline 100g",                   count: 3 },
  { spoken: "fair and lovely", product: "Glow & Lovely 50g",               count: 3 },
  { spoken: "glow and lovely", product: "Glow & Lovely 50g",               count: 3 },
  { spoken: "boroline",        product: "Boroline 40g",                    count: 3 },
  { spoken: "himani",          product: "Boroline 40g",                    count: 3 },
  { spoken: "ponds",           product: "Ponds Talc 100g",                 count: 2 },
  { spoken: "powder",          product: "Ponds Talc 100g",                 count: 2 },
  { spoken: "body lotion",     product: "Body Lotion",                     count: 2 },

  // ── Antiseptic & Hygiene ─────────────────────────────
  { spoken: "dettol",          product: "Dettol Antiseptic 100ml",         count: 3 },
  { spoken: "savlon",          product: "Savlon Antiseptic 100ml",         count: 3 },
  { spoken: "sanitizer",       product: "Hand Sanitizer 100ml",            count: 3 },

  // ── Washing & Household ──────────────────────────────
  { spoken: "surf excel",      product: "Surf Excel 500g",                 count: 3 },
  { spoken: "ariel",           product: "Ariel 500g",                      count: 3 },
  { spoken: "rin",             product: "Rin Detergent 500g",              count: 3 },
  { spoken: "wheel",           product: "Wheel Detergent 1kg",             count: 3 },
  { spoken: "tide",            product: "Tide Detergent 500g",             count: 3 },
  { spoken: "ghadi",           product: "Ghadi Detergent 1kg",             count: 3 },
  { spoken: "kapda dhone",     product: "Surf Excel 500g",                 count: 2 },
  { spoken: "washing powder",  product: "Surf Excel 500g",                 count: 2 },
  { spoken: "vim",             product: "Vim Dishwash 500g",               count: 3 },
  { spoken: "pril",            product: "Pril Dishwash 500ml",             count: 3 },
  { spoken: "bartan dhone",    product: "Vim Dishwash 500g",               count: 2 },
  { spoken: "dishwash",        product: "Vim Dishwash 500g",               count: 2 },
  { spoken: "harpic",          product: "Harpic 500ml",                    count: 3 },
  { spoken: "lizol",           product: "Lizol 500ml",                     count: 3 },
  { spoken: "colin",           product: "Colin 500ml",                     count: 3 },
  { spoken: "odonil",          product: "Odonil Air Freshener",            count: 3 },
  { spoken: "hit",             product: "Hit Cockroach Spray",             count: 3 },
  { spoken: "mortein",         product: "Mortein Mosquito Coil",           count: 3 },
  { spoken: "good knight",     product: "Good Knight Coil",                count: 3 },
  { spoken: "allout",          product: "All Out Machine",                 count: 3 },

  // ── Baby Care ────────────────────────────────────────
  { spoken: "pampers",         product: "Pampers Diapers",                 count: 3 },
  { spoken: "huggies",         product: "Huggies Diapers",                 count: 3 },
  { spoken: "diaper",          product: "Pampers Diapers",                 count: 2 },
  { spoken: "johnsons baby",   product: "Johnson Baby Powder 100g",        count: 3 },
  { spoken: "baby powder",     product: "Johnson Baby Powder 100g",        count: 2 },
  { spoken: "cerelac",         product: "Nestlé Cerelac 300g",             count: 3 },

  // ── Cooking Essentials ───────────────────────────────
  { spoken: "soya sauce",      product: "Soya Sauce 200ml",                count: 3 },
  { spoken: "vinegar",         product: "Vinegar 500ml",                   count: 3 },
  { spoken: "tomato sauce",    product: "Maggi Tomato Ketchup 500g",       count: 3 },
  { spoken: "ketchup",         product: "Maggi Tomato Ketchup 500g",       count: 3 },
  { spoken: "catchup",         product: "Maggi Tomato Ketchup 500g",       count: 3 },
  { spoken: "mayonnaise",      product: "Hellmanns Mayonnaise 200g",       count: 2 },
  { spoken: "mayo",            product: "Hellmanns Mayonnaise 200g",       count: 2 },
  { spoken: "pickle",          product: "Pickle 200g",                     count: 2 },
  { spoken: "achar",           product: "Pickle 200g",                     count: 2 },
  { spoken: "papad",           product: "Lijjat Papad 200g",               count: 3 },
  { spoken: "lijjat",          product: "Lijjat Papad 200g",               count: 3 },
  { spoken: "vermicelli",      product: "Bambino Vermicelli 900g",         count: 3 },
  { spoken: "seviyan",         product: "Bambino Vermicelli 900g",         count: 3 },
  { spoken: "sevai",           product: "Bambino Vermicelli 900g",         count: 2 },

  // ── Bread & Bakery ───────────────────────────────────
  { spoken: "bread",           product: "Bread",                           count: 2 },
  { spoken: "roti",            product: "Bread",                           count: 2 },
  { spoken: "pav",             product: "Pav Buns",                        count: 3 },
  { spoken: "double roti",     product: "Bread",                           count: 3 },

  // ── Misc Household ───────────────────────────────────
  { spoken: "matchbox",        product: "Matchbox",                        count: 3 },
  { spoken: "maachis",         product: "Matchbox",                        count: 3 },
  { spoken: "agarbatti",       product: "Agarbatti",                       count: 3 },
  { spoken: "camphor",         product: "Camphor",                         count: 3 },
  { spoken: "kapoor",          product: "Camphor",                         count: 3 },
  { spoken: "dhoop",           product: "Dhoop Sticks",                    count: 3 },
  { spoken: "tissue",          product: "Tissue Paper",                    count: 2 },
  { spoken: "napkin",          product: "Tissue Paper",                    count: 2 },
  { spoken: "carry bag",       product: "Plastic Bags",                    count: 2 },
  { spoken: "polythene",       product: "Plastic Bags",                    count: 2 },
  { spoken: "theli",           product: "Plastic Bags",                    count: 2 },

  // ── Regional: Gujarati spoken forms ─────────────────
  { spoken: "bhaat",           product: "Sona Masoori Rice 5kg",           count: 2 },
  { spoken: "khaand",          product: "Sugar 1kg",                       count: 3 },
  { spoken: "bateta",          product: "Potato",                          count: 3 },
  { spoken: "tameta",          product: "Tomato",                          count: 3 },
  { spoken: "jeeru",           product: "Cumin Seeds 100g",                count: 3 },
  { spoken: "methi",           product: "Methi Seeds 100g",                count: 3 },

  // ── Regional: Punjabi spoken forms ──────────────────
  { spoken: "makki",           product: "Maize Flour 1kg",                 count: 3 },
  { spoken: "kanak",           product: "Aashirvaad Atta 5kg",             count: 2 },
  { spoken: "gehun",           product: "Aashirvaad Atta 5kg",             count: 2 },

  // ── Regional: Marathi spoken forms ──────────────────
  { spoken: "tandool",         product: "Sona Masoori Rice 5kg",           count: 3 },
  { spoken: "kaanda",          product: "Onion",                           count: 3 },
  { spoken: "batata",          product: "Potato",                          count: 3 },
  { spoken: "kothimbir",       product: "Tata Sampann Coriander",          count: 3 },
  { spoken: "shengdana",       product: "Groundnut Oil 1L",                count: 2 },
  { spoken: "mohari",          product: "Mustard Seeds 100g",              count: 3 },
  { spoken: "halad",           product: "Tata Sampann Turmeric 200g",      count: 3 },

  // ── Regional: Bengali spoken forms ──────────────────
  { spoken: "chaal",           product: "Sona Masoori Rice 5kg",           count: 3 },
  { spoken: "musur dal",       product: "Masoor Dal 1kg",                  count: 3 },
  { spoken: "chhola",          product: "Kabuli Chana 1kg",                count: 3 },
  { spoken: "peyaj",           product: "Onion",                           count: 3 },
  { spoken: "begun",           product: "Brinjal",                         count: 3 },
  { spoken: "halud",           product: "Tata Sampann Turmeric 200g",      count: 3 },
  { spoken: "sorisha",         product: "Mustard Seeds 100g",              count: 3 },
  { spoken: "doi",             product: "Amul Curd 400g",                  count: 3 },

  // ── Regional: Malayalam spoken forms ────────────────
  { spoken: "ari",             product: "Sona Masoori Rice 5kg",           count: 3 },
  { spoken: "cherupayar",      product: "Moong Dal 1kg",                   count: 3 },
  { spoken: "uzhunnu",         product: "Urad Dal 1kg",                    count: 3 },
  { spoken: "kadala",          product: "Kabuli Chana 1kg",                count: 3 },
  { spoken: "kaduku",          product: "Mustard Seeds 100g",              count: 3 },
  { spoken: "jeerakam",        product: "Cumin Seeds 100g",                count: 3 },
  { spoken: "malli",           product: "Tata Sampann Coriander",          count: 3 },
  { spoken: "manjapu",         product: "Tata Sampann Turmeric 200g",      count: 3 },
  { spoken: "thenga enna",     product: "Parachute Coconut Oil 500ml",     count: 3 },
]
